name: example
description: A sample command-line application.
version: 1.0.0

publish_to: "none"

environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  usecase:
    path: "../"
  sealed_result: ^3.0.0

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.6
