name: usecase
description: Small component that encapsulates an application's scenario logic.
repository: https://github.com/hugo-pcl/usecase
version: 1.1.0

environment:
  sdk: ^3.1.0

dependencies:
  meta: ^1.9.1
  sealed_result: ^3.0.0

dev_dependencies:
  melos: ^3.1.1
  test: ^1.24.6
